fix NPL: stop passing node to showConfirmDialog()
because when no other mind maps are open, `root` isn't visible, resulting in
java.lang.NullPointerException: Cannot invoke "org.freeplane.view.swing.map.MapView.getNodeView(org.freeplane.features.map.NodeModel)" because "this.selectedMapView" is null
	at org.freeplane.view.swing.map.MapViewController.scrollNodeToVisible(MapViewController.java:721)
	at org.freeplane.core.ui.components.UITools.showConfirmDialog(UITools.java:477)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at io.github.macmarrum.freeplane.ScriptOnMapOpen.executeScriptOnMapOpen(macmarrumScriptOnMapOpen.groovy:50)